### ISSUE TITLE
Support IPv6 addresses in URLs and check ports more strictly

### ISSUE THREAD

**Issue by melloc** [davepacheco/kang#3]
IPv6 addresses can be used in URLs like `http://[::1]/` or `http://[::1]:8080`. Attempting to use this with kang results in it splitting at the first colon:

```shell
% ./bin/kang.js -h 'http://[::1]:8080'

/home/cody/src/kang-2/lib/kang.js:92
                        throw (new Error('invalid port: "' + portstr + '"'));
                               ^
Error: invalid port: ":1]:8080"
...
```

Or, if you use an address that doesn't have two colons in a row, `parseInt()` stops parsing at the first nonnumeric character, and allows kang to push on through with a bad hostname:

```shell
% ./bin/kang.js -h 'http://[fd00:2cb::1]:8080'
failed to fetch snapshots: first of 1 error: getaddrinfo ENOTFOUND
> snapshot: index out of range
```

`parseInt()` will also permit things like:

```shell
% ./bin/kang.js -h 'http://127.0.0.1:8080abcd'
```

I initially tried changing kang over to using `mod_url.parse()`, but that seems to have its own set of issues with bad input:

```
> url.parse('http://example.com:foo')
{ protocol: 'http:',
  slashes: true,
  auth: null,
  host: 'example.com',
  port: null,
  hostname: 'example.com',
  hash: null,
  search: null,
  query: null,
  pathname: '/:foo',
  path: '/:foo',
  href: 'http://example.com/:foo' }
```

So I've instead extended `knMakeSource()` to handle these types of URLs and do better checking of the port string.

**Comment by davepacheco** [comment]
Integrated.
